# Generated by Django 5.2.1 on 2025-07-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_order_created_at_alter_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='conversation_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
